name: Download Test

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Check system
        run: |
          echo "CPU:"
          nproc
          echo ""
          echo "RAM:"
          free -h
          echo ""
          echo "Disk:"
          df -h

      - name: Install yt-dlp
        run: |
          python3 -m pip install --upgrade yt-dlp

      - name: Download video
        run: |
          yt-dlp \
            --no-playlist \
            -f "bv*+ba/b" \
            --merge-output-format mp4 \
            -o "video.%(ext)s" \
            "https://cdn.maktabkhooneh.org/videos/7409694809949324.mp4?expire=1788466970&token=10c1cac70255dad3dee049abfa835c87&md5=EMHKxwJV2tPe4Emr-oNchw=="

      - name: Check downloaded file
        run: |
          ls -lh
          du -sh .
